version: '3.6'

services:

  postgres:
    build: ./postgres
    restart: always
    volumes:
    - db_data:/var/lib/postgressql/data
    ports:
      - 6432:5432
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - "postgres"

    # default setup at ${POSTGRES_DB} database which needs to be created
  graphql-engine:
    image: hasura/graphql-engine:v1.3.3
    ports:
    - "8090:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: adminsecret

volumes:
  db_data:
  elasticsearch-data:
    driver: local